server:
  port: ${PORT:8182}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

spring:
  application:
    name: split-with-room-mates

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://mysql-1541e490-udayfoundation2025-bf90.l.aivencloud.com:27059/defaultdb?ssl-mode=REQUIRED}
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD:}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${SHOW_SQL:false}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true